name       : dbus
version    : 1.10.18
release    : 19
source     :
    - https://dbus.freedesktop.org/releases/dbus/dbus-1.10.18.tar.gz : 6049ddd5f3f3e2618f615f1faeda0a115104423a7996b7aa73e2f36e38cc514a
license    :
    - GPL-2.0
    - LGPL-2.1
summary    :
    - System Message Daemon
    - launch : X11 dbus-launch helper
description: |
    D-Bus is a message bus system, a simple way for applications to talk to one
    another. D-Bus supplies both a system daemon (for events such as
    "new hardware device added" or "printer queue changed") and a per-user
    login-session daemon (for general IPC needs among user applications).
    Also, the message bus is built on top of a general one-to-one message
    passing framework, which can be used by any two applications to communicate
    directly (without going through the message bus daemon).
component  :
    - system.base
    - launch : desktop.core
patterns   :
    - devel : /usr/lib64/dbus-1.0/include/
    - 32bit-devel : /usr/lib32/dbus-1.0/include/
    - launch :
        - /usr/bin/dbus-launch
        - /usr/share/man/man1/dbus-launch.1
builddeps  :
    - pkgconfig32(expat)
    - pkgconfig32(glib-2.0)
    - pkgconfig32(libudev)
    - pkgconfig32(x11)
    - docbook-xml
    - xmlto
emul32     : yes
setup      : |
    %patch -p1 < $pkgfiles/no-fatal-warnings.patch
    %configure --prefix=/usr \
               --libexecdir=%libdir%/dbus-1.0 \
               --with-console-auth-dir=/run/console/ \
               --with-systemdsystemunitdir=/usr/lib/systemd/system \
               --with-system-pid-file=/run/dbus/pid \
               --with-system-socket=/run/dbus/system_bus_socket \
               --enable-epoll \
               --enable-user-session \
               --disable-static
build      : |
    %make
install    : |
    %make_install
    rm -rf $installdir/var
    if [[ ! -z "${EMUL32BUILD}" ]]; then
        rm -v $installdir/%libdir%/dbus-1.0/dbus-daemon-launch-helper
    else
        chmod o+x $installdir/%libdir%/dbus-1.0/dbus-daemon-launch-helper
        install -D -m 00644 $pkgfiles/dbus.tmpfiles $installdir/%libdir%/tmpfiles.d/dbus.conf
        install -D -m 00644 $pkgfiles/dbus.sysusers $installdir/%libdir%/sysusers.d/dbus.conf
    fi
