name       : dbus
version    : 1.12.8
release    : 26
source     :
    - https://dbus.freedesktop.org/releases/dbus/dbus-1.12.8.tar.gz : e2dc99e7338303393b6663a98320aba6a63421bcdaaf571c8022f815e5896eb3
license    :
    - GPL-2.0
    - LGPL-2.1
summary    :
    - System Message Daemon
    - launch : X11 dbus-launch helper
description: |
    D-Bus is a message bus system, a simple way for applications to talk to one
    another. D-Bus supplies both a system daemon (for events such as
    "new hardware device added" or "printer queue changed") and a per-user
    login-session daemon (for general IPC needs among user applications).
    Also, the message bus is built on top of a general one-to-one message
    passing framework, which can be used by any two applications to communicate
    directly (without going through the message bus daemon).
component  :
    - system.base
    - devel: system.devel
    - launch : desktop.core
patterns   :
    - devel : /usr/lib64/dbus-1.0/include/
    - 32bit-devel : /usr/lib32/dbus-1.0/include/
    - launch :
        - /usr/bin/dbus-launch
        - /usr/share/man/man1/dbus-launch.1
builddeps  :
    - pkgconfig32(expat)
    - pkgconfig32(glib-2.0)
    - pkgconfig32(liblzma)
    - pkgconfig32(gudev-1.0)
    - pkgconfig32(libudev)
    - pkgconfig32(x11)
    - libgcrypt-32bit-devel
    - docbook-xml
    - xmlto
emul32     : yes
optimize   :
    - size
    - lto
setup      : |
    %patch -p1 < $pkgfiles/0001-dbus-Teach-it-a-new-trick-Shutting-up.patch
    %patch -p1 < $pkgfiles/0001-Add-run-dbus-tmpfiles.patch

    %configure --libexecdir=%libdir%/dbus-1.0 \
               --with-console-auth-dir=/run/console/ \
               --with-systemdsystemunitdir=/usr/lib64/systemd/system \
               --with-systemduserunitdir=/usr/lib64/systemd/user \
               --with-system-pid-file=/run/dbus/pid \
               --with-system-socket=/run/dbus/system_bus_socket \
               --enable-epoll \
               --enable-user-session \
               --disable-static
build      : |
    %make
install    : |
    %make_install
    rm -rf $installdir/var
    if [[ ! -z "${EMUL32BUILD}" ]]; then
        rm -v $installdir/%libdir%/dbus-1.0/dbus-daemon-launch-helper
    else
        chmod o+x $installdir/%libdir%/dbus-1.0/dbus-daemon-launch-helper
    fi
